server:
  port: 8080
spring:
  profiles:
    active: druid
  # jackson时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    # 项目名
    name: blog-xxgg

mybatis-plus:
  #扫描 *mapper.xml 文件
  mapper-locations: classpath:mapper/*.xml
  #如果不使用type-aliases-package，则在每个实体类前加上@Component即可
  type-aliases-package: com.xxgg.blog.model.po
  configuration:
    #自动转化命名
    map-underscore-to-camel-case: true
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      # 去掉表前缀
#      table-prefix: blog_

#log配置
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
